<?php

/**
 * @file
 * Contains avs_integration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function avs_integration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the avs_integration module.
    case 'help.page.avs_integration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('AVS Integration') . '</p>';
      return $output;

    default:
  }
}
